name:                mortar
version:             0.1.0.0
github:              "stridervc/mortar"
license:             BSD3
author:              "Fred Strauss"
maintainer:          "fred@strider.co.za"
copyright:           "2020 Fred Strauss &lt;fred@strider.co.za&gt;"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stridervc/mortar#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - sdl2
  - sdl2-ttf
  - sdl2-image
  - linear
  - ghc
  - text

executables:
  simple:
    main:   Simple.hs
    source-dirs:    examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mortar
    - sdl2

tests:
  mortar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mortar
